### PR TITLE
Update mainnet-voting-entities.md

### PR DESCRIPTION
**Pull request by PaulieB14**
fixed entities that were not correct format.

### CODE REVIEW

**Comment by PaulieB14** [comment]
@pemulis Hey this is the fix for entites.

**Comment by PaulieB14** [comment]
@pemulis just following up to see if you can put this through to fix entities

**Comment by PaulieB14** [comment]
@pemulis @evaldofelipe Wanted to submit this fix to entities on docs website

**Review by smb2796 — APPROVED** [review]
Thank you @PaulieB14, and sorry for the delay! Looks good

**Pull request merged**
